# nixhold host install <name> [--remote <user>@<ip>] [--disk <by-id>]
#                             [--disko-from <path>] [--yes]
#
# NixOS: generates a single-disk disko layout (unless --disko-from is
# given), ships the host's cached SSH key via --extra-files so agenix
# decrypts on first activation, and drives nixos-anywhere
# (--build-on-remote: the target builds its own closure;
# --generate-hardware-config nixos-facter: writes facter.json back).
#
# Darwin: local, fresh-macOS capable (see nh_darwin_install) — ensures
# the host age identity at /etc/ssh, commits/rekeys the recipient, and
# activates via the fleet's pinned nix-darwin even when darwin-rebuild
# isn't on PATH yet.
#
# NOTE: the live install path (SSH to target, nixos-anywhere) cannot
# be exercised in CI; the deterministic parts (disko generation, key
# staging, command construction) are. The framework ships ONE disko
# shape — single disk, GPT, no encryption; power users pass
# --disko-from for anything else.

# nh_write_disko <device> <out> — emit a single-disk GPT disko module.
nh_write_disko() {
  local device="$1" out="$2"
  mkdir -p "$(dirname "$out")"
  cat >"$out" <<EOF
# Generated by \`nixhold host install\`. Single disk, GPT, no
# encryption. Edit by hand or replace via \`--disko-from\` if you need
# a different layout.
{
  disko.devices.disk.main = {
    type = "disk";
    device = "${device}";
    content = {
      type = "gpt";
      partitions = {
        ESP = {
          size = "512M";
          type = "EF00";
          content = {
            type = "filesystem";
            format = "vfat";
            mountpoint = "/boot";
          };
        };
        root = {
          size = "100%";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
      };
    };
  };
}
EOF
}

# nh_pick_disk <remote> — list the target's whole disks and prompt for
# the root disk; print a stable /dev/disk/by-id path (falling back to
# /dev/<name> if no by-id alias resolves).
nh_pick_disk() {
  local remote="$1" json opts chosen name byid
  json="$(nh_ssh "$remote" -- lsblk -dnJ -o NAME,SIZE,TYPE,MODEL 2>/dev/null)" || {
    nh_err "lsblk over ssh failed against $remote"
    return 1
  }
  opts="$(printf '%s' "$json" | jq -r '.blockdevices[] | select(.type == "disk") | "\(.name)\t\(.size)\t\(.model // "?")"')"
  if [ -z "$opts" ]; then
    nh_err "no whole disks found on $remote"
    return 1
  fi
  chosen="$(printf '%s\n' "$opts" | gum choose --header "Root disk to install onto (ERASED):")" || return 1
  name="$(printf '%s' "$chosen" | cut -f1)"
  [ -n "$name" ] || return 1
  byid="$(nh_ssh "$remote" -- "for l in /dev/disk/by-id/*; do [ \"\$(readlink -f \"\$l\")\" = /dev/$name ] && { printf '%s' \"\$l\"; break; }; done" 2>/dev/null || true)"
  if [ -n "$byid" ]; then
    printf '%s' "$byid"
  else
    nh_warn "no /dev/disk/by-id alias for $name; using /dev/$name (less stable)"
    printf '/dev/%s' "$name"
  fi
}

# nh_darwin_install <name> <root> — local darwin install, fresh-macOS
# capable. Does the three jobs the NixOS path gets from nixos-anywhere:
#   1. host age identity — ensure /etc/ssh/ssh_host_ed25519_key exists
#      (agenix's darwin identityPath): install the `host add`-cached
#      key, or generate one in place;
#   2. recipients — commit that key's pubkey as
#      keys/hosts/<name>/host.pub and rekey secrets when it changed;
#   3. activate — sudo darwin-rebuild; on a machine that has never
#      switched (no darwin-rebuild on PATH), bootstrap via the fleet's
#      pinned nix-darwin.
nh_darwin_install() {
  local name="$1" root="$2"

  if [ "$(uname -s)" != "Darwin" ]; then
    nh_err "darwin install runs on the Mac itself — run this on $name"
    return 1
  fi

  local hostkey="/etc/ssh/ssh_host_ed25519_key"
  local cache="$NIXHOLD_CACHE_DIR/host-keys/$name"

  # 1. Host identity. Fresh macOS has no /etc/ssh host keys until
  #    sshd has run at least once.
  if [ ! -f "$hostkey" ]; then
    sudo install -d -m 0755 /etc/ssh
    if [ -f "$cache/ssh_host_ed25519_key" ]; then
      nh_info "installing cached host key to $hostkey (sudo)"
      sudo install -m 0600 "$cache/ssh_host_ed25519_key" "$hostkey"
      sudo install -m 0644 "$cache/ssh_host_ed25519_key.pub" "$hostkey.pub"
    else
      nh_info "generating host key at $hostkey (sudo)"
      sudo ssh-keygen -t ed25519 -N "" -C "nixhold-host-$name" -f "$hostkey" >/dev/null
    fi
  fi
  if [ ! -f "$hostkey.pub" ]; then
    nh_info "deriving $hostkey.pub (sudo)"
    sudo sh -c "ssh-keygen -y -f '$hostkey' > '$hostkey.pub' && chmod 0644 '$hostkey.pub'"
  fi

  # 2. The committed recipient must be the machine's ACTUAL key —
  #    agenix decrypts with $hostkey, regardless of what host.pub says.
  local keys_dir committed machine_pub
  keys_dir="$(nh_worktree_keys_dir)"
  committed="$keys_dir/hosts/$name/host.pub"
  machine_pub="$(awk '{print $1 " " $2}' "$hostkey.pub")"
  if [ ! -f "$committed" ] || [ "$(awk '{print $1 " " $2}' "$committed")" != "$machine_pub" ]; then
    mkdir -p "$keys_dir/hosts/$name"
    cp "$hostkey.pub" "$committed"
    if git -C "$root" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
      git -C "$root" add --intent-to-add "$committed" 2>/dev/null || true
    fi
    nh_ok "committed $committed (the machine's host key)"
    nh_info "re-encrypting secrets to include the host recipient"
    . "$NIXHOLD_LIB_ROOT/secret-rekey.sh"
    cmd_secret_rekey || {
      nh_err "rekey failed — secrets are NOT decryptable by $name yet; fix and re-run install"
      return 1
    }
    nh_info "commit + push keys/ and secrets/ once the install finishes"
  fi

  # 3. Activate (nix-darwin requires root for switch).
  if command -v darwin-rebuild >/dev/null 2>&1; then
    (cd "$root" && sudo darwin-rebuild switch --flake ".#$name") || return $?
  else
    nh_info "darwin-rebuild not on PATH — first switch, bootstrapping via the fleet's pinned nix-darwin"
    local out
    out="$(mktemp -d -t nixhold-darwin-bootstrap.XXXXXX)"
    nix build --out-link "$out/system" "$root#darwinConfigurations.$name.system"
    if ! (cd "$root" && sudo "$out/system/sw/bin/darwin-rebuild" switch --flake ".#$name"); then
      rm -rf "$out"
      nh_err "first activation failed — if it complained about pre-existing files (/etc/nix/nix.conf, /etc/zshenv, …), move them aside (e.g. sudo mv /etc/nix/nix.conf{,.before-nix-darwin}) and re-run"
      return 1
    fi
    rm -rf "$out"
  fi

  nh_ok "installed $name"
  nh_info "agenix decrypts via launchd shortly after activation — verify: ls /run/agenix (kick it: sudo launchctl kickstart -k system/activate-agenix)"
}

cmd_host_install() {
  local name="" remote="" disk="" disko_from="" yes=0
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --remote) remote="$2"; shift 2 ;;
      --disk) disk="$2"; shift 2 ;;
      --disko-from) disko_from="$2"; shift 2 ;;
      --yes) yes=1; shift ;;
      -h | --help)
        cat <<'EOF'
Usage: nixhold host install <name> [--remote <user>@<ip>]
                                    [--disk <by-id>] [--disko-from <path>]
                                    [--yes]
EOF
        return 0
        ;;
      -*) nh_err "unknown flag: $1"; return 1 ;;
      *) if [ -z "$name" ]; then name="$1"; shift; else nh_err "extra arg: $1"; return 1; fi ;;
    esac
  done
  if [ -z "$name" ]; then
    nh_err "expected: nixhold host install <name>"
    return 1
  fi

  nh_require_cmd nix ssh jq
  local root platform arch
  root="$(nh_fleet_root)" || return 2
  platform="$(nh_host_platform "$name")" || {
    nh_err "host '$name' not found in fleet"
    return 1
  }
  arch="$(nh_host_eval "$name" "$platform" "nixhold.fleet.derived.self.arch" | jq -r '.')"

  case "$arch" in
    *-darwin)
      if [ -n "$remote" ]; then
        nh_warn "--remote is ignored for darwin hosts (install runs locally)"
      fi
      nh_darwin_install "$name" "$root"
      return $?
      ;;
    *-linux) ;;
    *)
      nh_err "unsupported arch: $arch"
      return 1
      ;;
  esac

  if [ -z "$remote" ]; then
    nh_err "--remote <user>@<ip> required for NixOS hosts (boot the target into a reachable SSH state first)"
    return 1
  fi

  local hostcfg_dir disko_target facter_target
  hostcfg_dir="$root/hosts/$name"
  disko_target="$hostcfg_dir/disko.nix"
  facter_target="$hostcfg_dir/facter.json"
  mkdir -p "$hostcfg_dir"

  # 1. Disk layout.
  if [ -n "$disko_from" ]; then
    cp "$disko_from" "$disko_target"
    nh_ok "copied disko layout from $disko_from"
  elif [ -f "$disko_target" ] && nh_prompt_confirm "Reuse existing $disko_target?"; then
    nh_info "reusing $disko_target"
  else
    if [ -z "$disk" ]; then
      nh_require_cmd gum
      disk="$(nh_pick_disk "$remote")" || return 1
    fi
    [ -n "$disk" ] || { nh_err "no disk selected"; return 1; }
    nh_write_disko "$disk" "$disko_target"
    nh_ok "wrote $disko_target (device $disk)"
  fi

  # 2. Confirm — this is the one destructive verb. The gum disk
  #    picker warns, but the --disk / --disko-from / reuse-existing
  #    paths would otherwise reformat with zero prompt.
  if [ "$yes" -ne 1 ]; then
    nh_warn "nixos-anywhere will ERASE the disk(s) declared in $disko_target on $name @ $remote and reinstall from scratch"
    nh_prompt_confirm "Proceed with the destructive install of $name?" || {
      nh_info "aborted"
      return 0
    }
  fi

  # 3. Stage the host's cached SSH key so agenix decrypts on the first
  #    activation pass (placed before nixos-install runs).
  #    nixos-anywhere is checked BEFORE key material lands in $TMPDIR,
  #    and the trap cleans the staging dir on every exit path.
  nh_require_cmd nixos-anywhere
  local cache extra
  cache="$NIXHOLD_CACHE_DIR/host-keys/$name"
  if [ ! -f "$cache/ssh_host_ed25519_key" ]; then
    nh_err "no cached host key at $cache — run 'nixhold host add $name' first"
    return 1
  fi
  extra="$(mktemp -d)"
  # shellcheck disable=SC2064 — expand $extra now, it goes out of scope
  trap "rm -rf '$extra'" EXIT
  mkdir -p "$extra/etc/ssh"
  install -m 0600 "$cache/ssh_host_ed25519_key" "$extra/etc/ssh/ssh_host_ed25519_key"
  install -m 0644 "$cache/ssh_host_ed25519_key.pub" "$extra/etc/ssh/ssh_host_ed25519_key.pub"

  nh_info "ensure hosts.$name.modules imports: ./hosts/$name/disko.nix, inputs.disko.nixosModules.disko, { nixhold.hardware.facterReport = ./hosts/$name/facter.json; }"

  # 4. Install. The target builds its own closure (--build-on-remote);
  #    nixos-facter writes the hardware report back to facter.json.
  nh_info "running nixos-anywhere against $name @ $remote"
  if nixos-anywhere \
    --flake "$root#$name" \
    --generate-hardware-config nixos-facter "$facter_target" \
    --extra-files "$extra" \
    --build-on-remote \
    --target-host "$remote"; then
    nh_ok "installed $name"
    nh_info "commit the generated hardware files: $disko_target and $facter_target"
  else
    local rc=$?
    nh_err "nixos-anywhere failed (exit $rc)"
    return "$rc"
  fi
}
