# nixhold host install <name> [--remote <user>@<ip>] [--disk <by-id>]
#                             [--disko-from <path>]
#
# NixOS: generates a single-disk disko layout (unless --disko-from is
# given), ships the host's cached SSH key via --extra-files so agenix
# decrypts on first activation, and drives nixos-anywhere
# (--build-on-remote: the target builds its own closure;
# --generate-hardware-config nixos-facter: writes facter.json back).
#
# Darwin: runs darwin-rebuild switch locally (the Mac is its own
# target).
#
# NOTE: the live install path (SSH to target, nixos-anywhere) cannot
# be exercised in CI; the deterministic parts (disko generation, key
# staging, command construction) are. The framework ships ONE disko
# shape — single disk, GPT, no encryption; power users pass
# --disko-from for anything else.

# nh_write_disko <device> <out> — emit a single-disk GPT disko module.
nh_write_disko() {
  local device="$1" out="$2"
  mkdir -p "$(dirname "$out")"
  cat >"$out" <<EOF
# Generated by \`nixhold host install\`. Single disk, GPT, no
# encryption. Edit by hand or replace via \`--disko-from\` if you need
# a different layout.
{
  disko.devices.disk.main = {
    type = "disk";
    device = "${device}";
    content = {
      type = "gpt";
      partitions = {
        ESP = {
          size = "512M";
          type = "EF00";
          content = {
            type = "filesystem";
            format = "vfat";
            mountpoint = "/boot";
          };
        };
        root = {
          size = "100%";
          content = {
            type = "filesystem";
            format = "ext4";
            mountpoint = "/";
          };
        };
      };
    };
  };
}
EOF
}

# nh_pick_disk <remote> — list the target's whole disks and prompt for
# the root disk; print a stable /dev/disk/by-id path (falling back to
# /dev/<name> if no by-id alias resolves).
nh_pick_disk() {
  local remote="$1" json opts chosen name byid
  json="$(nh_ssh "$remote" -- lsblk -dnJ -o NAME,SIZE,TYPE,MODEL 2>/dev/null)" || {
    nh_err "lsblk over ssh failed against $remote"
    return 1
  }
  opts="$(printf '%s' "$json" | jq -r '.blockdevices[] | select(.type == "disk") | "\(.name)\t\(.size)\t\(.model // "?")"')"
  if [ -z "$opts" ]; then
    nh_err "no whole disks found on $remote"
    return 1
  fi
  chosen="$(printf '%s\n' "$opts" | gum choose --header "Root disk to install onto (ERASED):")" || return 1
  name="$(printf '%s' "$chosen" | cut -f1)"
  [ -n "$name" ] || return 1
  byid="$(nh_ssh "$remote" -- "for l in /dev/disk/by-id/*; do [ \"\$(readlink -f \"\$l\")\" = /dev/$name ] && { printf '%s' \"\$l\"; break; }; done" 2>/dev/null || true)"
  if [ -n "$byid" ]; then
    printf '%s' "$byid"
  else
    nh_warn "no /dev/disk/by-id alias for $name; using /dev/$name (less stable)"
    printf '/dev/%s' "$name"
  fi
}

cmd_host_install() {
  local name="" remote="" disk="" disko_from=""
  while [ "$#" -gt 0 ]; do
    case "$1" in
      --remote) remote="$2"; shift 2 ;;
      --disk) disk="$2"; shift 2 ;;
      --disko-from) disko_from="$2"; shift 2 ;;
      -h | --help)
        cat <<'EOF'
Usage: nixhold host install <name> [--remote <user>@<ip>]
                                    [--disk <by-id>] [--disko-from <path>]
EOF
        return 0
        ;;
      -*) nh_err "unknown flag: $1"; return 1 ;;
      *) if [ -z "$name" ]; then name="$1"; shift; else nh_err "extra arg: $1"; return 1; fi ;;
    esac
  done
  if [ -z "$name" ]; then
    nh_err "expected: nixhold host install <name>"
    return 1
  fi

  nh_require_cmd nix ssh jq
  local root platform arch
  root="$(nh_fleet_root)" || return 2
  platform="$(nh_host_platform "$name")" || {
    nh_err "host '$name' not found in fleet"
    return 1
  }
  arch="$(nh_host_eval "$name" "$platform" "nixhold.fleet.derived.self.arch" | jq -r '.')"

  case "$arch" in
    *-darwin)
      if [ -n "$remote" ]; then
        nh_warn "--remote is ignored for darwin hosts (install runs locally)"
      fi
      nh_require_cmd darwin-rebuild
      (cd "$root" && darwin-rebuild switch --flake ".#$name")
      return $?
      ;;
    *-linux) ;;
    *)
      nh_err "unsupported arch: $arch"
      return 1
      ;;
  esac

  if [ -z "$remote" ]; then
    nh_err "--remote <user>@<ip> required for NixOS hosts (boot the target into a reachable SSH state first)"
    return 1
  fi

  local hostcfg_dir disko_target facter_target
  hostcfg_dir="$root/hosts/$name"
  disko_target="$hostcfg_dir/disko.nix"
  facter_target="$hostcfg_dir/facter.json"
  mkdir -p "$hostcfg_dir"

  # 1. Disk layout.
  if [ -n "$disko_from" ]; then
    cp "$disko_from" "$disko_target"
    nh_ok "copied disko layout from $disko_from"
  elif [ -f "$disko_target" ] && nh_prompt_confirm "Reuse existing $disko_target?"; then
    nh_info "reusing $disko_target"
  else
    if [ -z "$disk" ]; then
      nh_require_cmd gum
      disk="$(nh_pick_disk "$remote")" || return 1
    fi
    [ -n "$disk" ] || { nh_err "no disk selected"; return 1; }
    nh_write_disko "$disk" "$disko_target"
    nh_ok "wrote $disko_target (device $disk)"
  fi

  # 2. Stage the host's cached SSH key so agenix decrypts on the first
  #    activation pass (placed before nixos-install runs).
  local cache extra
  cache="$NIXHOLD_CACHE_DIR/host-keys/$name"
  if [ ! -f "$cache/ssh_host_ed25519_key" ]; then
    nh_err "no cached host key at $cache — run 'nixhold host add $name' first"
    return 1
  fi
  extra="$(mktemp -d)"
  mkdir -p "$extra/etc/ssh"
  install -m 0600 "$cache/ssh_host_ed25519_key" "$extra/etc/ssh/ssh_host_ed25519_key"
  install -m 0644 "$cache/ssh_host_ed25519_key.pub" "$extra/etc/ssh/ssh_host_ed25519_key.pub"

  nh_info "ensure hosts.$name.modules imports: ./hosts/$name/disko.nix, inputs.disko.nixosModules.disko, { nixhold.hardware.facterReport = ./hosts/$name/facter.json; }"

  # 3. Install. The target builds its own closure (--build-on-remote);
  #    nixos-facter writes the hardware report back to facter.json.
  nh_require_cmd nixos-anywhere
  nh_info "running nixos-anywhere against $name @ $remote"
  if nixos-anywhere \
    --flake "$root#$name" \
    --generate-hardware-config nixos-facter "$facter_target" \
    --extra-files "$extra" \
    --build-on-remote \
    --target-host "$remote"; then
    rm -rf "$extra"
    nh_ok "installed $name"
    nh_info "commit the generated hardware files: $disko_target and $facter_target"
  else
    local rc=$?
    rm -rf "$extra"
    nh_err "nixos-anywhere failed (exit $rc)"
    return "$rc"
  fi
}
