#!/usr/bin/env bash
# nixhold — single-entrypoint CLI for nixhold-managed fleets.
#
# All subcommands are sourced (not exec'd) so they share the
# helper-lib state and the operator's TTY. The runtime is shipped
# as a `writeShellApplication`; `runtimeInputs` already places
# gum, nix, jq, ssh, etc. on PATH.
set -euo pipefail

# Resolve where this script lives so sourced subcommands can be
# located regardless of cwd. Inside the writeShellApplication
# wrapper, BASH_SOURCE[0] points at the unwrapped script path.
NIXHOLD_LIB_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export NIXHOLD_LIB_ROOT

# Every CLI nix call needs flakes — but a fresh machine (vanilla Nix,
# pre-first-switch) hasn't enabled them yet. `extra-` merges harmlessly
# where they're already on; a caller-set NIX_CONFIG is preserved.
NIX_CONFIG="${NIX_CONFIG:+$NIX_CONFIG
}extra-experimental-features = nix-command flakes"
export NIX_CONFIG

# shellcheck source=lib/run.sh
. "$NIXHOLD_LIB_ROOT/lib/run.sh"
# shellcheck source=lib/prompt.sh
. "$NIXHOLD_LIB_ROOT/lib/prompt.sh"
# shellcheck source=lib/fleet.sh
. "$NIXHOLD_LIB_ROOT/lib/fleet.sh"
# shellcheck source=lib/ssh.sh
. "$NIXHOLD_LIB_ROOT/lib/ssh.sh"
# shellcheck source=lib/secrets.sh
. "$NIXHOLD_LIB_ROOT/lib/secrets.sh"
# shellcheck source=lib/escrow.sh
. "$NIXHOLD_LIB_ROOT/lib/escrow.sh"

# One process-wide exit path: wipes the scratch root (host keys, the
# repo deploy key, unwrapped identities) and runs whatever rollback a
# verb registered with nh_at_exit. Signals run it too, so a Ctrl-C
# mid-rotation is rolled back rather than left half-applied.
trap nh_run_at_exit EXIT
trap 'nh_run_at_exit; exit 130' INT
trap 'nh_run_at_exit; exit 143' TERM
# A closed terminal (ssh session dropped, terminal window shut) is the
# other way a verb dies mid-flight with plaintext staged.
trap 'nh_run_at_exit; exit 129' HUP

usage() {
  cat <<'EOF'
nixhold — manage a nixhold-declared fleet. An argument in [brackets]
opens a picker when left out.

Hosts:
  host add [<name>]                 Register a host: keys, secrets, then install.
  host install [<name>] [--remote …] Reformat a host (the picker adds "new host…").
  host key <name> [--remote …]      Make machine and repo agree about its host key.
  host rotate-key <name> [--remote …] New host key: escrow, rekey, install it.
  host remove [<name>]              Delete a host from the fleet.

Daily:
  deploy [<name>…] [--mode …]       Build + activate; no name picks the hosts.
  update [--yes]                    Pull, update inputs, show what moved, deploy.
  status [<name>] [--fleet]         Declared services, endpoints, secrets.
  logs [<host>] [<service>]         Tail journald for a unit on a host.

Secrets:
  secret edit [<host>] [<name>]     Provision a missing secret, or edit one.
  secret rekey                      Re-encrypt all secrets to current recipients.

Framework:
  iso [--flash <device>]            Build (and write) the fleet installer image.
  service new <name>                Scaffold a service module.
  lint [--strict]                   Convention + invariant checks.
EOF
}

# Two-token verbs ("host add", "secret edit", …) get joined into
# one subcommand-script name so the dispatcher stays flat.
main() {
  if [ "$#" -eq 0 ]; then
    usage
    exit 0
  fi

  case "$1" in
    -h | --help | help)
      usage
      exit 0
      ;;
    iso | deploy | update | status | lint | logs)
      verb="$1"
      shift
      . "$NIXHOLD_LIB_ROOT/$verb.sh"
      cmd_"$verb" "$@"
      ;;
    host)
      shift
      if [ "$#" -eq 0 ]; then
        nh_err "expected 'host <verb>'"
        exit 1
      fi
      sub="$1"
      shift
      case "$sub" in
        add | install | key | remove | rotate-key)
          . "$NIXHOLD_LIB_ROOT/host-$sub.sh"
          cmd_host_"${sub//-/_}" "$@"
          ;;
        escrow | install-key)
          nh_err "'host $sub' was folded into 'host key <name>'"
          exit 1
          ;;
        *)
          nh_err "unknown 'host' subcommand: $sub"
          exit 1
          ;;
      esac
      ;;
    secret)
      shift
      if [ "$#" -eq 0 ]; then
        nh_err "expected 'secret <verb>'"
        exit 1
      fi
      sub="$1"
      shift
      case "$sub" in
        edit | rekey)
          . "$NIXHOLD_LIB_ROOT/secret-$sub.sh"
          cmd_secret_"${sub}" "$@"
          ;;
        new | bootstrap)
          nh_err "'secret $sub' was folded into 'secret edit [<host>] [<name>]'"
          exit 1
          ;;
        *)
          nh_err "unknown 'secret' subcommand: $sub"
          exit 1
          ;;
      esac
      ;;
    service)
      shift
      if [ "${1:-}" != "new" ]; then
        nh_err "expected 'service new <name>'"
        exit 1
      fi
      shift
      . "$NIXHOLD_LIB_ROOT/service-new.sh"
      cmd_service_new "$@"
      ;;
    init)
      nh_err "'init' is gone — the operator identity is generated by the first 'host add' on a fleet that has none"
      exit 1
      ;;
    profile)
      nh_err "'profile new' is gone — copy a shipped profile from nixhold/profiles/ into your profilesDir"
      exit 1
      ;;
    *)
      nh_err "unknown command: $1"
      usage
      exit 1
      ;;
  esac
}

main "$@"
