# Facter report wiring + first-install guard. NixOS-only.
#
# The operator points `nixhold.hardware.facterReport` at the host's
# nixos-facter report (`nixhold host install` generates it after kexec,
# before the closure build). Until the file exists the host still
# EVALUATES — so `nix eval`, `nixhold lint`, and `nixhold status` work —
# but a build is blocked by an assertion. Because nixos-anywhere
# evaluates the disko script (which doesn't force `assertions`), kexecs,
# writes the report, then builds the closure, the assertion only ever
# trips on a plain rebuild of an un-installed host, not during install.
#
# The `hardware.facter` option set ships in nixpkgs — no extra input.
{ config, lib, ... }:
let
  cfg = config.nixhold.hardware;
  declared = cfg.facterReport != null;
  present = declared && builtins.pathExists cfg.facterReport;
in
{
  options.nixhold.hardware.facterReport = lib.mkOption {
    type = lib.types.nullOr lib.types.path;
    default = null;
    example = lib.literalExpression "./facter.json";
    description = ''
      Path to this NixOS host's nixos-facter hardware report.
      Generated by `nixhold host install`. When the file exists it is
      wired to `hardware.facter.reportPath`; until then the host still
      evaluates but a build is blocked by an assertion pointing at
      `nixhold host install`. Set this instead of assigning
      `hardware.facter.reportPath` directly, so the framework owns the
      pre-install guard.
    '';
  };

  config = lib.mkMerge [
    (lib.mkIf present {
      hardware.facter.reportPath = cfg.facterReport;
    })
    (lib.mkIf (declared && !present) {
      assertions = [
        {
          assertion = false;
          message = ''
            nixhold.hardware.facterReport (${toString cfg.facterReport}) does not
            exist yet — run `nixhold host install <host>` to generate it,
            then commit it.
          '';
        }
      ];
    })
  ];
}
